# Generated by Django 3.1.5 on 2021-01-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_character_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateExample',
        ),
        migrations.DeleteModel(
            name='NullExample',
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='movie',
            new_name='movies',
        ),
    ]
